name: Daily Crypto Ranking

on:
  workflow_dispatch:

jobs:
  run-ranking:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Ranking
        env:
          DISCORD_WEBHOOK_RANKING: ${{ secrets.DISCORD_WEBHOOK_RANKING }}
          DISCORD_WEBHOOK_DEBUG_LOG: ${{ secrets.DISCORD_WEBHOOK_DEBUG_LOG }}
        run: python main.py --ranking
